# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eddf3c0f85e327fa9fbce6f4218c359b7ffe238751b04924a36eab13745ae0c7d162737b85ac3088184da86d88ace12f7bdfb2d6e4674712fc42ab30cc0e29a6

test:
  secret_key_base: b925a7723a5f54e9fede278458c838024c0c5caf950d9ae9f5017a251e0b741c4c842823dee8ae9e1316878ba5a77b6cc6b0932bb52d28f95cafc79f5d1223df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
